In [13]:
import numpy as np
 
class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
        
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)
            

In [14]:
if __name__ == '__main__':
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

In [15]:
d = np.array([0, 0, 0, 1])
 
perceptron = Perceptron(input_size=2)
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]


In [16]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [17]:
d

array([0, 0, 0, 1])

In [18]:
mp = Perceptron(5) #(100*100)
x = np.asarray([-10,-2,-30,-4,-50])
mp.predict(x)

1

In [19]:
mp.activation_fn(10)

1

In [20]:
mp.W

array([0., 0., 0., 0., 0., 0.])

# 1- Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.

init:Perceptron oluşturmamızı sağlar.Veri sayısını girdi olarak alırız. Girilen veri sayısını arttırmamızın sebebi sapmayı dahil edebilmektir. Öğrenme sayısı ve devir sayısı değiştirilebilir bir parametredir.

activation_fn: Aktivasyon fonksiyonu için 0 ve 1 olarak eşik değerlerini belirlemiş oluyoruz. Buna göre outpuları alıyoruz.

predict: Verilen girdiler sonucunda çıktı almamızı sağlar. Bias değeri eklendikten son iç çarpım yaparak sonrasında activation fonksiyonunu kullanırız. Sonuç olarak Inputun sonucu tahmini edilir.

fit: Makineyi eğittiğimiz fonksiyondur. X ile d bilgileri kullanıcıdan alınarak weight (w) değerlerinin iteratif olarak incelenmesini sağlar.



# 2- XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.


In [21]:
if __name__ == '__main__':
    X = np.array([  
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
    
 
 

In [23]:
 d = np.array([0, 1, 1, 0])

In [25]:
perceptron = Perceptron(input_size=2)
print(perceptron.W)

[0. 0. 0.]


In [26]:
perceptron.fit(X, d)
perceptron.W

array([ 0., -1.,  0.])

In [28]:
print(perceptron.predict(np.asarray([0,0]))) 
print(perceptron.predict(np.asarray([0,1]))) 
print(perceptron.predict(np.asarray([1,0]))) 
print(perceptron.predict(np.asarray([1,1]))) 

1
1
0
0


# 3- Bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız.

 x değerlerimiz input ve d değerlerimiz outputtur. 40 öğrencinin imzası bir dizide tutulur.ınput olarak öğrenci imzaları verilir output olarak imzanın kime ait olduğu beklenir.


# 4- Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.

Modelin hatası o anki değer ile gerçek değer arasındaki fark hesaplanarak elde edilir. Error fonksiyonu üzerinde iteratif olarak ilerleyerek devam edilir. Elde edilen değer ile hedeften çok sapma riski vardır. Çözüm olarak error 0 olana kadar ya da belirli bir adıma kadar ilerletilir.
Bu adım sayısı çoğaltılarak hedefe yakınlaşılabilir.
